# Generated by Django 4.2.30 on 2026-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_rename_judge_notif_recip_i_0f60e0_idx_judge_notif_recipie_9180e7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-date'], name='judge_submi_problem_1d8475_idx'),
        ),
    ]
