# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0234_remove_problem_suggester'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='replay_version',
            field=models.IntegerField(default=0),
        ),
    ]
