# Generated by Django 5.2.16 on 2026-07-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0235_contest_replay_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('tri_ky', 'Tri kỷ'), ('chi_em', 'Chị em'), ('ban_be', 'Bạn bè'), ('cap_doi', 'Cặp đôi'), ('lop_du_phong', 'Lốp dự phòng')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='relationship name')),
                ('max_per_user', models.IntegerField(default=5, verbose_name='max per user')),
            ],
            options={
                'verbose_name': 'relationship type',
                'verbose_name_plural': 'relationship types',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_sent', to='judge.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_received', to='judge.profile')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.relationshiptype')),
            ],
            options={
                'verbose_name': 'relationship',
                'verbose_name_plural': 'relationships',
                'unique_together': {('from_user', 'to_user', 'relationship_type')},
            },
        ),
    ]
