# Generated by Django 5.2.16 on 2026-07-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_add_relationship_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='pending_type_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_type_changes', to='judge.relationshiptype'),
        ),
    ]
