# Generated by Django 5.2.16 on 2026-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0237_add_pending_type_change'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('from_user', 'to_user'), name='unique_accepted_relationship_per_pair'),
        ),
    ]
