# Generated by Django 5.2.16 on 2026-07-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0238_add_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='type_change_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_change_requests', to='judge.profile'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='key',
            field=models.CharField(choices=[('tri_ky', 'Tri kỷ'), ('chi_em', 'Chị em'), ('anh_em', 'Anh em'), ('cap_doi', 'Cặp đôi'), ('lop_du_phong', 'Lốp dự phòng')], max_length=20, unique=True),
        ),
    ]
